services:
  - type: web
    name: community-activity-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_NAME
        value: pbl6
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
    healthCheckPath: /
    autoDeploy: true
